In [1]:
# Operación suma

# Operación flotante

# Operaciones con string

# Enteros

In [2]:
edad = 25        # un entero
cantidad = -100  # también pueden ser negativos
print(type(edad))  # <class 'int'>

<class 'int'>

In [3]:
x = 10
y = 3
print(x + y)   # suma → 13
print(x - y)   # resta → 7
print(x * y)   # multiplicación → 30
print(x // y)  # división entera → 3
print(x % y)   # módulo → 1

13
7
30
3
1

# Decimales

In [4]:
pi = 3.1416
altura = 1.75
print(type(pi))  # <class 'float'>

<class 'float'>

In [5]:
a = 5.0
b = 2
print(a / b)   # división normal → 2.5
print(a ** b)  # potencia → 25.0

2.5
25.0

# Cadenas de texto (string)

In [6]:
nombre = "Ana"
saludo = 'Hola'
print(type(nombre))  # <class 'str'>

<class 'str'>

In [7]:
texto = "Python"
print(texto[0])       # acceso → 'P'
print(texto[-1])      # último carácter → 'n'
print(texto.upper())  # mayúsculas → 'PYTHON'
print(texto.lower())  # minúsculas → 'python'
print(texto + " 3.10") # concatenación → 'Python 3.10'

P
n
PYTHON
python
Python 3.10

# Comparacion entre tipos

In [8]:
# int → float
x = 5
print(float(x))   # 5.0

5.0

In [9]:
# float → int
y = 3.9
print(int(y))     # 3 (trunca, no redondea)

3

In [10]:
# string → int/float
numero = "42"
print(int(numero))    # 42

42

In [11]:
decimal = "3.14"
print(float(decimal)) # 3.14

3.14

In [12]:
# int/float → string
z = 100
print(str(z))   # "100"

100

# 📝 Ejercicio: Crear y usar variables en Python  

## Enunciado  
Crea tres variables en Python:  

- `nombre` (cadena de texto, ejemplo: `"Ana"`)  
- `edad` (número entero, ejemplo: `15`)  
- `altura` (número decimal, ejemplo: `1.60`)  

Con esas variables:  

1. Muestra el mensaje en pantalla:
   
   Ana tiene 15 años y mide 1.60 metros.


2. Calcula y muestra:  
- La edad dentro de **2 años**.  
- La altura en **centímetros**.

# Comparaciones


# Operadores en Python

| Operador      | Descripción                                             | Ejemplo                       |
| ------------- | ------------------------------------------------------- | ----------------------------- |
| `==`          | Igual a: Compara si dos valores son iguales             | `5 == 5` (True)               |
| `!=`          | No igual a: Compara si dos valores no son iguales       | `5 != 3` (True)               |
| `>`           | Mayor que: Compara si el valor de la izquierda es mayor | `5 > 3` (True)                |
| `<`           | Menor que: Compara si el valor de la izquierda es menor | `5 < 3` (False)               |
| `>=`          | Mayor o igual que                                        | `5 >= 3` (True)               |
| `<=`          | Menor o igual que                                        | `5 <= 5` (True)               |
| `and`         | Operador lógico AND: Devuelve True si ambos son True     | `True and False` (False)      |
| `or`          | Operador lógico OR: Devuelve True si al menos uno es True| `True or False` (True)        |
| `not`         | Operador lógico NOT: Invierte el valor lógico            | `not True` (False)            |
| `is`          | Operador de identidad: Compara si dos objetos son el mismo| `x is y`                      |
| `in`          | Operador de pertenencia: Comprueba si un valor está en una secuencia | `'a' in 'abc'` (True)  |

In [13]:
x = 12
y = 8
x is y

False

In [14]:
# Ejemplos de python
0.3 == 0.1+0.1+0.1

False

In [15]:
None > 0

TypeError: '>' not supported between instances of 'NoneType' and 'int'

In [16]:
import math 

math.nan == math.nan

False

In [17]:
-0.0 == 0.0

True

In [18]:
"10"==10

False

In [19]:
[] == None

False

In [20]:
[] is None

False




| A     | B     | A and B | A or B  |
| ----- | ----- | ------- | ------- |
| True  | True  | True    | True    |
| True  | False | False   | True    |
| False | True  | False   | True    |
| False | False | False   | False   |

In [21]:
x = True 
y = not True

In [22]:
0 and 0

0

# La polilla del abedul

¿Cómo cambia la frecuencia de polillas claras y oscuras entre bosques limpios y contaminados?

Bernard Kettlewell
(Kettlewell 1955, 1956).

El procedimiento experimental:

1. Se capturan polillas.

2. Se marcan (para reconocerlas después).

4. Se liberan en el bosque.

4. Más tarde se vuelven a capturar polillas en trampas.

5. Si una polilla marcada aparece otra vez en la captura, entonces está recapturada.

In [90]:
from datascience import *
moths = Table().with_columns("tipo", ["clara", "oscura"], "liberadas" , [64, 154], "atrapadas" ,  [16, 82])
moths

tipo   | liberadas | atrapadas
clara  | 64        | 16
oscura | 154       | 82

In [91]:
moths.column("atrapadas").dtype

dtype('int64')

In [94]:
tasas = moths.column("atrapadas")/moths.column("liberadas")
tasas

array([ 0.25      ,  0.53246753])

In [101]:
moths.append_column("tasa", tasas )

tipo   | liberadas | atrapadas | tasa
clara  | 64        | 16        | 0.25
oscura | 154       | 82        | 0.532468

In [102]:
# Otro ejemplo

In [103]:
moths = Table().with_columns(
    "moth_id", [1,2,3,4,5],  # Tabla con numeros enteros
    "moth_id_as_string", ["1","2","3","4","5"],  # Tabla con numeros enteros
    "color", ["dark","light","light","dark","light"],# Tabla con variables tipo string
    "forest", ["polluted","polluted","clean","clean","polluted"]# Tabla con variables tipo string
)
moths

moth_id | moth_id_as_string | color | forest
1       | 1                 | dark  | polluted
2       | 2                 | light | polluted
3       | 3                 | light | clean
4       | 4                 | dark  | clean
5       | 5                 | light | polluted

In [104]:
moths
moths.select("color")

color
dark
light
light
dark
light

In [105]:
moths.group("color")

color | count
dark  | 2
light | 3

In [42]:
moths.where("moth_id_as_string","1")

moth_id | moth_id_as_string | color | forest
1       | 1                 | dark  | polluted

## Mas tablas

In [106]:
moths = Table().with_columns(
    "moth_id", [1,2,3,4,5,6,7,8,9,10,
                11,12,13,14,15,16,17,18,19,20],
    
    "color", ["dark","light","dark","light","dark",
              "light","light","dark","dark","light",
              "dark","light","dark","light","dark",
              "light","light","dark","dark","light"],
    
    "forest", ["polluted","polluted","polluted","clean","polluted",
               "clean","clean","polluted","clean","clean",
               "polluted","polluted","polluted","clean","polluted",
               "clean","clean","polluted","polluted","clean"]
)

In [108]:
moths.group("forest")
moths.where("forest","polluted")
moths.pivot("color","forest")

forest   | dark | light
clean    | 1    | 8
polluted | 9    | 2

# Secuencias

##  Arreglos

In [ ]:
from datascience import *
make_array(1, 2,2, 3, )

array([1, 2, 2, 3])

In [ ]:
# Multiplicación, división

In [ ]:
type(make_array(1, 2,2, 3, ))

numpy.ndarray

In [ ]:
temperatura = make_array(23, 25, 26, 28, )

Pasemos los valores de temperatura a kelvin

In [ ]:
temperatura + 273

array([296, 298, 299, 301])

In [ ]:
q = make_array("hola", "mundo")
q

array(['hola', 'mundo'],
      dtype='<U5')

## Funciones sobre arreglos

Tomado de [data 8 book](https://inferentialthinking.com/chapters/05/1/Arrays.html)

## Tabla 1: Funciones de agregación

| Función           | Descripción                                                     |
|-------------------|-----------------------------------------------------------------|
| `np.prod`         | Multiplica todos los elementos                                  |
| `np.sum`          | Suma todos los elementos                                        |
| `np.all`          | Verifica si todos los elementos son verdaderos (números diferentes de 0 son verdaderos) |
| `np.any`          | Verifica si alguno de los elementos es verdadero (números diferentes de 0 son verdaderos) |
| `np.count_nonzero`| Cuenta el número de elementos diferentes de cero                |



## Tabla 2: Funciones de transformación numérica

| Función           | Descripción                                                     |
|-------------------|-----------------------------------------------------------------|
| `np.diff`         | Diferencia entre elementos adyacentes                            |
| `np.round`        | Redondea cada número al entero más cercano                       |
| `np.cumprod`      | Producto acumulado: para cada elemento, multiplica todos los elementos hasta ese punto |
| `np.cumsum`       | Suma acumulada: para cada elemento, suma todos los elementos hasta ese punto |
| `np.exp`          | Eleva cada elemento a la exponencial                             |
| `np.log`          | Aplica el logaritmo natural a cada elemento                      |
| `np.sqrt`         | Calcula la raíz cuadrada de cada elemento                        |
| `np.sort`         | Ordena los elementos                                             |


## Tabla 3: Funciones para manipulación de strings

| Función            | Descripción                                                    |
|--------------------|----------------------------------------------------------------|
| `np.char.lower`     | Convierte cada elemento a minúsculas                           |
| `np.char.upper`     | Convierte cada elemento a mayúsculas                           |
| `np.char.strip`     | Elimina espacios al principio o al final de cada elemento      |
| `np.char.isalpha`   | Verifica si cada elemento contiene solo letras (sin números ni símbolos) |
| `np.char.isnumeric` | Verifica si cada elemento contiene solo números (sin letras)   |



## Tabla 4: Funciones de búsqueda en strings

| Función             | Descripción                                                  |
|---------------------|--------------------------------------------------------------|
| `np.char.count`      | Cuenta cuántas veces aparece una cadena de búsqueda en los elementos del arreglo |
| `np.char.find`       | Devuelve la posición en la que se encuentra la cadena de búsqueda por primera vez en cada elemento |
| `np.char.rfind`      | Devuelve la posición en la que se encuentra la cadena de búsqueda por última vez en cada elemento |
| `np.char.startswith` | Verifica si cada elemento comienza con la cadena de búsqueda |

In [ ]:
import numpy as np

In [ ]:
make_array(...)

array([Ellipsis], dtype=object)

In [ ]:
q=make_array("por la", "libertad")
np.char.upper(q)

array(['POR LA', 'LIBERTAD'],
      dtype='<U8')

# Aumento de la presión con la profundidad

Los tiburones zorro viven principalmente en océanos tropicales y subtropicales, y uno de los lugares donde se observan con frecuencia es alrededor de Malapascua Island en Philippines. Allí es uno de los pocos sitios del mundo donde buzos pueden verlos casi todos los días.

Los estudios  muestran un patrón muy interesante, durante la noche suelen subir a aguas más superficiales para cazar peces pequeños como sardinas y caballas. En cambio, durante el día descienden a mayores profundidades, generalmente entre 20 y 40 metros, donde visitan zonas conocidas como estaciones de limpieza. Allí pequeños peces limpiadores eliminan parásitos de su piel y de sus branquias.

Este comportamiento implica que el tiburón experimenta cambios de profundidad a lo largo del día y, por tanto, también cambios en la presión del agua que lo rodea. Para describir cómo aumenta esa presión con la profundidad, puede emplearse el siguiente modelo físico:


\begin{equation}
P = P_0 + \rho g h
\end{equation}

Donde:
- $P$ es la presión total a una determinada profundidad.
- $P_0$ es la presión atmosférica a nivel del mar: 1atm es 101.325 pascales (Pa)
- $\rho$ es la densidad del agua (aproximadamente 1000 kg/m³ para agua dulce).
- $g$ es la aceleración gravitacional (aproximadamente 9.81 m/s²).
- $h$ es la profundidad en metros.

1. Calcular la presión en atmósferas para las siguientes profundidades:

```
h = 0, 10, 20, 30, 40, 50 m
```

2. Determinar el aumento diferencial de presión, es decir hacer el cálculo de la diferencia entre el primer y segundo valor, entre el tercero y segundo y asi sucesivamente: emplea `np.diff`

In [ ]:
np.diff(h)

array([10, 10, 10, 10, 10])

In [ ]:
notas = make_array(2.5, 4.5, 5.0)
promedio = np.sum(notas)/len(notas)
promedio

4.0

In [ ]:
promedio = np.mean(notas)
promedio

4.0

# Rangos

Enfatizar en la diferencia entre diferentes tipos de datos y los rangos

In [109]:
u = np.arange(5)
u

NameError: name 'np' is not defined

In [110]:
u.take(2)

NameError: name 'u' is not defined

## Leibniz's Formula for Pi

La fórmula de Leibniz para calcular $\pi$ es una serie infinita alternada que converge hacia $\pi$ cuando se multiplica por 4. Se puede expresar de la siguiente manera:

\begin{equation}
\frac{\pi}{4} = 1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \cdots
\end{equation}

También se puede reorganizar la fórmula separando los términos positivos y negativos en dos series distintas:

\begin{equation}
\frac{\pi}{4} = \left( 1 + \frac{1}{5} + \frac{1}{9} + \cdots \right) - \left( \frac{1}{3} + \frac{1}{7} + \frac{1}{11} + \cdots \right)
\end{equation}

Esta fórmula es una representación elegante de $\pi$,  aunque su convergencia es relativamente lenta.

¿Calcular el valor de pi?

------------

In [ ]:
tabla_periodica = Table().with_columns( ["temperatura", ["Si", "K", "Fe", "Co"], "NumeroAtomico", [14,19,26,27] ])
tabla_periodica.take(range(1, 2))

temperatura | NumeroAtomico
K           | 19

In [ ]:
tabla_periodica.select("NumeroAtomico")

NumeroAtomico
14
19
26
27

In [ ]:
tabla_periodica.column("NumeroAtomico")

array([14, 19, 26, 27])

#  Repaso de tablas

| **Método**                                  | **Descripción**                                                                 |
|---------------------------------------------|---------------------------------------------------------------------------------|
| `Table.read_table(file_path)`               | Lee un archivo CSV y devuelve una tabla.                                        |
| `table.show(n)`                             | Muestra las primeras `n` filas de la tabla.                                     |
| `table.with_columns(column1, values1, ...)` | Agrega una o más columnas nuevas a la tabla.                                    |
| `table.column(column_name)`                 | Devuelve los valores de una columna como un array de Numpy.                     |
| `table.num_columns()`                       | Devuelve el número de columnas en la tabla.                                     |
| `table.num_rows()`                          | Devuelve el número de filas en la tabla.                                        |
| `table.select(column_name1, column_name2)`  | Selecciona y devuelve una tabla con solo las columnas indicadas.                |
| `table.drop(column_name1, column_name2)`    | Elimina las columnas especificadas y devuelve una tabla nueva.                  |
| `table.where(column_name, predicate)`       | Filtra las filas según una condición en una columna específica.                 |
| `table.sort(column_name, descending=False)` | Ordena la tabla por una columna en orden ascendente o descendente.              |

## Creacion de una tabla 
Supongamos que queremos construir una tabla con las distancia al sol,  y la masa de cada planeta.

| Planeta    | Distancia al Sol (UA) | Masa (Unidades de masas terrestres) |
|------------|-----------------------|-------------------------------------|
| Mercurio   | 0.39                  | 0.055                              |
| Venus      | 0.72                  | 0.815                              |
| Tierra     | 1.00                  | 1.000                              |
| Marte      | 1.52                  | 0.107                              |
| Júpiter    | 5.20                  | 317.8                              |
| Saturno    | 9.58                  | 95.2                               |
| Urano      | 19.22                 | 14.5                               |
| Neptuno    | 30.05                 | 17.1                               |

Nota:  
- 1 UA ≈ 149.6 millones de kilómetros
- 5.97 × 10²⁴ kilogramos.

Las siguientes celdas contiene la informaciòn par no copiar todos los datos: 

```python 
distancias_ua = [0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.22, 30.05]
```

```python 
masas_terrestres = [0.055, 0.815, 1.000, 0.107, 317.8, 95.2, 14.5, 17.1]
```

In [ ]:
from  datascience import *

In [ ]:
# Construyendo la tabla
Table().with_columns(["Planeta", ["Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"],
                      "DistanciaSol", [0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.22, 30.05],
                      "Masa", [0.055, 0.815, 1.000, 0.107, 317.8, 95.2, 14.5, 17.1],                     
                     ])

Planeta  | DistanciaSol | Masa
Mercurio | 0.39         | 0.055
Venus    | 0.72         | 0.815
Tierra   | 1            | 1
Marte    | 1.52         | 0.107
Júpiter  | 5.2          | 317.8
Saturno  | 9.58         | 95.2
Urano    | 19.22        | 14.5
Neptuno  | 30.05        | 17.1

In [ ]:
# Almacenado la tabla en una variable
planetas=Table().with_columns(["Nombre", ["Mercurio", "Venus", "Tierra", "Marte", "Júpiter", "Saturno", "Urano", "Neptuno"],
                      "DistanciaSol", [0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.22, 30.05],
                      "Masa", [0.39, 0.72, 1.00, 1.52, 5.20, 9.58, 19.22, 30.05],                     
                     ])
planetas

Nombre   | DistanciaSol | Masa
Mercurio | 0.39         | 0.39
Venus    | 0.72         | 0.72
Tierra   | 1            | 1
Marte    | 1.52         | 1.52
Júpiter  | 5.2          | 5.2
Saturno  | 9.58         | 9.58
Urano    | 19.22        | 19.22
Neptuno  | 30.05        | 30.05

## table.take
## table.show

In [ ]:
planetas.take(0)

Nombre   | DistanciaSol | Masa
Mercurio | 0.39         | 0.39

In [ ]:
planetas.select("Nombre")

Nombre
Mercurio
Venus
Tierra
Marte
Júpiter
Saturno
Urano
Neptuno

In [ ]:
planetas.labels

('Nombre', 'DistanciaSol', 'Masa')

In [ ]:
planetas.rows

Rows(Nombre   | DistanciaSol | Masa
Mercurio | 0.39         | 0.39
Venus    | 0.72         | 0.72
Tierra   | 1            | 1
Marte    | 1.52         | 1.52
Júpiter  | 5.2          | 5.2
Saturno  | 9.58         | 9.58
Urano    | 19.22        | 19.22
Neptuno  | 30.05        | 30.05)

In [ ]:
len(planetas)

3

In [ ]:
planetas.sort("Masa", descending=False)

Nombre   | DistanciaSol | Masa
Mercurio | 0.39         | 0.39
Venus    | 0.72         | 0.72
Tierra   | 1            | 1
Marte    | 1.52         | 1.52
Júpiter  | 5.2          | 5.2
Saturno  | 9.58         | 9.58
Urano    | 19.22        | 19.22
Neptuno  | 30.05        | 30.05

In [ ]:
planetas.drop("Masa")

Nombre   | DistanciaSol
Mercurio | 0.39
Venus    | 0.72
Tierra   | 1
Marte    | 1.52
Júpiter  | 5.2
Saturno  | 9.58
Urano    | 19.22
Neptuno  | 30.05

# Lectura de tablas

1. Muestra los 10 primeros valores de la tabla

2. Selecciona las columnas "Animal" y "Velocidad Promedio (km/h)"

3. Determina el animal que tiene mayor peso

In [ ]:
animals = Table().read_table("Animales_.csv")
animals

Unnamed: 0 | Animal                     | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
0          | Cerdo Hormiguero           | 117.5       | 52.5      | 40
1          | Lobo Terrícola             | 45          | 11        | 27
2          | Elefante Africano          | 290         | 4350      | 25
3          | León Africano              | 95          | 185       | 58
4          | Perro Salvaje Africano     | 77.5        | 27        | 56
5          | Íbice Alpino               | 84          | 69.5      | 60
6          | Rana de la Selva Amazónica | 7.5         | 0         | 0.55
7          | Bisonte Americano          | 169         | nan       | 48
8          | Oso Hormiguero             | 71.5        | 31.5      | 24
9          | Caballo Árabe              | 150         | 690       | 65
... (168 rows omitted)

In [ ]:
animales = animals.drop("Unnamed: 0")
animales

Animal                     | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Cerdo Hormiguero           | 117.5       | 52.5      | 40
Lobo Terrícola             | 45          | 11        | 27
Elefante Africano          | 290         | 4350      | 25
León Africano              | 95          | 185       | 58
Perro Salvaje Africano     | 77.5        | 27        | 56
Íbice Alpino               | 84          | 69.5      | 60
Rana de la Selva Amazónica | 7.5         | 0         | 0.55
Bisonte Americano          | 169         | nan       | 48
Oso Hormiguero             | 71.5        | 31.5      | 24
Caballo Árabe              | 150         | 690       | 65
... (168 rows omitted)

# Operacion sobre tablas


## Predicados

| Predicado                     | Descripción                                                  |
| ------------------------------| ------------------------------------------------------------ |
| `are.equal_to(Z)`              | Igual a Z                                                    |
| `are.above(x)`                 | Mayor que x                                                  |
| `are.above_or_equal_to(x)`     | Mayor o igual a x                                            |
| `are.below(x)`                 | Menor que x                                                  |
| `are.below_or_equal_to(x)`     | Menor o igual a x                                            |
| `are.between(x, y)`            | Mayor o igual a x y menor que y                              |
| `are.strictly_between(x, y)`   | Mayor que x y menor que y                                    |
| `are.between_or_equal_to(x, y)`| Mayor o igual a x y menor o igual a y                        |
| `are.containing(S)`            | Contiene la cadena de texto S                                |

## Predicados Negados

Puedes especificar la negación de cualquiera de estas condiciones utilizando `.not_` antes del predicado:

| Predicado Negado               | Descripción                                                  |
| ------------------------------| ------------------------------------------------------------ |
| `are.not_equal_to(Z)`          | No igual a Z                                                 |
| `are.not_above(x)`             | No mayor que x                                               |

In [ ]:
animales.where("Altura (cm)", are.above(100))

Animal                       | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Cerdo Hormiguero             | 117.5       | 52.5      | 40
Elefante Africano            | 290         | 4350      | 25
Bisonte Americano            | 169         | nan       | 48
Caballo Árabe                | 150         | 690       | 65
Arowana                      | 120         | 6         | 24
Elefante Asiático            | 250         | 3500      | 40
Delfín Moteado del Atlántico | 225         | 130       | 52
Foca de Pelo Australiana     | 136         | 29        | 32
Tiburón Peregrino            | 1100        | 550       | 21
Rinoceronte Negro            | 156         | nan       | 56
... (56 rows omitted)

In [ ]:
animales.where('Velocidad Promedio (km/h)', are.equal_to(48))

Animal            | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Bisonte Americano | 169         | nan       | 48
Tapir de Baird    | 91.5        | 275       | 48
Oso Pardo         | 95          | 425       | 48
Zorro Rojo        | 42.5        | 5         | 48
Tapir             | 95          | 275       | 48

In [ ]:
animales.where('Velocidad Promedio (km/h)', are.between(40,40))

Animal                | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Cerdo Hormiguero      | 117.5       | 52.5      | 40
Elefante Asiático     | 250         | 3500      | 40
Frailecillo Atlántico | 27.5        | 560       | 40
Zorro de Bengala      | 37.5        | 3.25      | 40
Ballena Azul          | 33          | 200       | 40
Chimpancé             | 160         | 48        | 40
Gorila del Este       | 164         | 138.5     | 40
Camarón Mantis        | 30          | 2         | 40
Gorila de Montaña     | 160         | 135       | 40
Oso Polar             | 160         | 700       | 40
... (5 rows omitted)

In [ ]:
animales.where('Animal', are.containing('Tiburón'))

Animal                      | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Tiburón Peregrino           | 1100        | 550       | 21
Tiburón Duende              | 320         | 210       | 2.3
Tiburón Blanco              | 610         | 2268      | 56
Tiburón Blanco              | 670         | 2268      | 56
Tiburón Mako de Aleta Corta | 394         | 800       | 45
Tiburón Ballena             | 1800        | 1500      | 70
Tiburón Cebra               | 330         | 32        | 20

In [ ]:
animales.sort("Velocidad Promedio (km/h)", descending = True)

Animal                   | Altura (cm) | Peso (kg) | Velocidad Promedio (km/h)
Águila Calva             | 86          | 4.5       | 120
Guepardo                 | 80          | 46        | 112
Berrendo                 | 92.5        | 55        | 88.5
Búho Nival               | 61.5        | 2.45      | 80
Lince Ibérico            | 65          | 11.5      | 75
Camarón Mantis Pavo Real | 18          | 0         | 72
Tiburón Ballena          | 1800        | 1500      | 70
Caballo Árabe            | 150         | 690       | 65
Tigre de Bengala         | 100         | 240       | 65
Perro Bóxer              | 58          | 28.5      | 64
... (168 rows omitted)

In [ ]:
animales.select("Animal")

Animal
Cerdo Hormiguero
Lobo Terrícola
Elefante Africano
León Africano
Perro Salvaje Africano
Íbice Alpino
Rana de la Selva Amazónica
Bisonte Americano
Oso Hormiguero
Caballo Árabe
... (168 rows omitted)

In [ ]:
animales.column("Animal")

array(['Cerdo Hormiguero', 'Lobo Terrícola', 'Elefante Africano',
       'León Africano', 'Perro Salvaje Africano', 'Íbice Alpino',
       'Rana de la Selva Amazónica', 'Bisonte Americano', 'Oso Hormiguero',
       'Caballo Árabe', 'Órix Árabe', 'Zorro Ártico', 'Arowana',
       'Elefante Asiático', 'Frailecillo Atlántico',
       'Delfín Moteado del Atlántico', 'Foca de Pelo Australiana',
       'Ajolote', 'Aye-Aye', 'Tapir de Baird', 'Águila Calva',
       'Civeta de Palma Banded', 'Macaco de Berbería', 'Tiburón Peregrino',
       'Dragón Barbudo', 'Zorro de Bengala', 'Tigre de Bengala',
       'Rinoceronte Negro', 'Arrendajo Azul', 'Ballena Azul',
       'Piquero de Patas Azules', 'Bonobo', 'Orangután de Borneo',
       'Delfín Nariz de Botella', 'Perro Bóxer', 'Oso Pardo',
       'Pitón Birmana', 'Capibara', 'Guepardo', 'Chimpancé', 'Pez Payaso',
       'Celacanto', 'Delfín Común', 'Sifaca de Coquerel', 'Perro Dálmata',
       'Cuón', 'Dingo', 'Dugongo', 'Gorila del Este', 'Equidna',
       'Pingüino Emperador', 'Tití Emperador', 'Erizo Europeo',
       'Zorro Fennec', 'Salamandra Común', 'Zorro Volador', 'Fosa',
       'Lagarto con Volante', 'GalÃ¡pagos Penguin',
       'Pingüino de Galápagos', 'Tortuga de Galápagos', 'Gaur', 'Gerenuc',
       'Gavial', 'Pulpo Gigante del Pacífico', 'Panda Gigante',
       'Monstruo de Gila', 'Rana de Cristal', 'Tiburón Duende',
       'Tití León Dorado', 'Rana Venenosa Dorada', 'Tiburón Blanco',
       'Tiburón Blanco', 'Tortuga Marina Verde', 'Tortuga Marina Verde',
       'Cebra de Grevy', 'Pez Bruja', 'Foca Arpa', 'Águila Arpía',
       'Hipopótamo', 'Cangrejo Herradura', 'Colibrí', 'Ballena Jorobada',
       'Lince Ibérico', 'Indri', 'Avispón Gigante Japonés',
       'Macaco Japonés', 'Kakapo', 'Rata Canguro', 'Cobra Real', 'Kiwi',
       'Dragón de Komodo', 'Geco de Cola de Hoja', 'Lémur', 'Lémur',
       'Macaco Cola de León', 'Ave Lira', 'Manatí', 'Mandril',
       'Lobo de Crin', 'Camarón Mantis', 'Markhor', 'Suricata',
       'Gorila de Montaña', 'Rata Topo Desnuda', 'Narval', 'Numbat',
       'Okapi', 'Okapi', 'Orangután', 'Pangolín', 'Mara Patagónica',
       'Camarón Mantis Pavo Real', 'Armadillo Hada Rosa', 'Ornitorrinco',
       'Oso Polar', 'Potoo', 'Mantis Religiosa', 'Mono Narigudo',
       'Berrendo', 'Pez Globo', 'Quokka', 'Zorro Rojo', 'Canguro Rojo',
       'Panda Rojo', 'Rottweiler', 'Saola', 'Ave Secretaria', 'Serval',
       'Picozapato', 'Tiburón Mako de Aleta Corta', 'Husky Siberiano',
       'Perezoso', 'Leopardo de las Nieves', 'Búho Nival',
       'Oso de Anteojos', 'Cachalote', 'Mono Araña', 'Hiena Manchada',
       'Mono Ardilla', 'Topo de Nariz Estrellada', 'Orangután de Sumatra',
       'Rinoceronte de Sumatra', 'Sumatran Rhinoceros', 'Sumatran Tiger',
       'Oso Malayo', 'Tapir', 'Tarsero', 'Diablo de Tasmania',
       'Tasmanian Tiger', 'Diablo Espinoso', 'Perezoso de Tres Dedos',
       'Mastín Tibetano', 'Tigre', 'Titanoboa', 'Tucán Toco',
       'Canguro Arborícola', 'Tuatara', 'Tufted Puffin', 'Uakari',
       'Murciélago Vampiro', 'Morsa', 'Jabalí Verrugoso', 'Búfalo de Agua',
       'Gorila Occidental', 'Western Lowland Gorilla', 'Tiburón Ballena',
       'Rinoceronte Blanco', 'Tigre Blanco', 'Jabalí', 'Ñu', 'Lobo',
       'Glotón', 'Wombat', 'Yak', 'Pingüino de Ojos Amarillos', 'Cebra',
       'Tiburón Cebra'],
      dtype='<U28')

Tarea de calse : Encontrar los osos cuya peso sea mayor a 100Kg

# Más de tablas

¿Cuál es la diferencia entre `select` y `column`, como nos podemos dar cuenta del tipo dato con lo que debemos trabajar?

Miremos la siguiente tabla analizando el número de atómico de algunos elementos químicos 

`El número atómico` es la cantidad de protones que se encuentran en el núcleo de un átomo de un elemento químico. 


```python
elementos = ["Hidrógeno", "Helio", "Litio", "Berilio", "Boro", "Carbono", "Nitrógeno", "Oxígeno", "Flúor", "Neón"]
numeros_atomicos = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


tabla_elementos = pd.DataFrame({
    "Elemento": elementos,
    "Número Atómico": numeros_atomicos
})
```